position:
    - rack1: [6.5, 0.75, 1.57]
    - rack2: [1.15, -2.2, 0.0]
    - rack3: [0.5, 2.05, 0.0]
    - arm: [6.3, -0.05, 3.14]
    - rack3_dock: [5.50, -0.05, 3.14]
    - rack2_dock: [6.30, -0.85, -1.57]

package_id: [3, 2, 1]