position:
    - rack1: [5.75, 0.6, 1.57]
    - rack2: [1.1, -2.3, 0.0]
    - rack3: [0.2, 1.8, 0.0]
    - arm: [6.3, -0.05, 3.14]
    - rack3_dock: [5.50, -0.05, 3.14]
    - rack2_dock: [6.50, -0.85, 1.57]

package_id: [3, 2, 1]
